// GET A NEWS
export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST"
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS"
export const GET_NEWS_ERROR = "GET_NEWS_ERROR"

// GET WORDPRESS NEWS
export const GET_WORDPRESS_NEWS_REQUEST = "GET_WORDPRESS_NEWS_REQUEST"
export const GET_WORDPRESS_NEWS_SUCCESS = "GET_WORDPRESS_NEWS_SUCCESS"
export const GET_WORDPRESS_NEWS_ERROR = "GET_WORDPRESS_NEWS_ERROR"

// GET A CATEGORY
export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR"

//NEWS UTILITY TYPES
export const CLEAR_NEWS_ERRORS = "CLEAR_NEWS_ERRORS"

// GET A NEWS
export const GET_NEWS_A_REQUEST = "GET_NEWS_A_REQUEST"
export const GET_NEWS_A_SUCCESS = "GET_NEWS_A_SUCCESS"
export const GET_NEWS_A_ERROR = "GET_NEWS_A_ERROR"

// ADD NEWS VIEWS
export const ADD_VIEW_REQUEST = "ADD_VIEW_REQUEST"
export const ADD_VIEW_SUCCESS = "ADD_VIEW_SUCCESS"
export const ADD_VIEW_ERROR = "ADD_VIEW_ERROR"

// FILTER_NEWS
export const FILTER_NEWS = "FILTER_NEWS"
export const CLEAR_FILTER = "CLEAR_FILTER"
