// export const EPISODE_PLAY_REQUEST = "EPISODE_PLAY_REQUEST"
// export const EPISODE_PLAYING = "EPISODE_PLAYING"
// export const EPISODE_PAUSE = "EPISODE_PAUSE"
// export const CURRENT_AUDIO = "CURRENT_AUDIO"

export const GET_PODCASTS_REQUEST = "GET_PODCASTS_REQUEST"
export const GET_PODCASTS_SUCCESS = "GET_PODCASTS_SUCCESS"
export const GET_PODCASTS_ERROR = "GET_PODCASTS_ERROR"

export const GET_SINGLE_PODCASTS_REQUEST = "GET_SINGLE_PODCASTS_REQUEST"
export const GET_SINGLE_PODCASTS_SUCCESS = "GET_SINGLE_PODCASTS_SUCCESS"
export const GET_SINGLE_PODCASTS_ERROR = "GET_SINGLE_PODCASTS_ERROR"

export const PLAY_EPISODE_REQUEST = "PLAY_EPISODE_REQUEST"
export const PLAY_EPISODE_SUCCESS = "PLAY_EPISODE_SUCCESS"
export const PLAY_EPISODE_ERROR = "PLAY_EPISODE_ERROR"
export const PAUSE_EPISODE = "PAUSE_EPISODE"
